#!/bin/bash

wait() {
    local file=$1
    local msg=${2:-Wait}
    until test -f $file ; do
        for c in '/' '-' '\' '|' ; do
            echo -ne "\r$msg... [$c]"
            sleep .5
        done
    done
    echo -e "\r$msg... Done"
}

wait /var/.dvc-installed "Installing DVC"
